apiVersion: v1
kind: Secret
metadata:
  name: calendar-mail-secret
type: Opaque
stringData:
  smtp-host: "sandbox.smtp.mailtrap.io"
  smtp-port: "2525"
  smtp-secure: "false"
  smtp-user: "e33a78dae7559d"
  smtp-pass: "14d3719af3c335"
  mail-from: "Collaborative Calendar <sandbox@example.com>"