apiVersion: apps/v1
kind: Deployment
metadata:
  name: calendar-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calendar-api
  template:
    metadata:
      labels:
        app: calendar-api
    spec:
      containers:
        - name: calendar-api
          image: pcdelight/calendar-api:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: "calendar-db-service"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "user"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: calendar-db-secret
                  key: db-password
            - name: DB_NAME
              value: "calendardb"
            - name: REDIS_HOST
              value: "calendar-redis-service"
            - name: REDIS_PORT
              value: "6379"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: calendar-api-secret
                  key: jwt-secret
            - name: SMTP_HOST
              valueFrom:
                secretKeyRef:
                  name: calendar-mail-secret
                  key: smtp-host

            - name: SMTP_PORT
              valueFrom:
                secretKeyRef:
                  name: calendar-mail-secret
                  key: smtp-port

            - name: SMTP_SECURE
              valueFrom:
                secretKeyRef:
                  name: calendar-mail-secret
                  key: smtp-secure

            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: calendar-mail-secret
                  key: smtp-user

            - name: SMTP_PASS
              valueFrom:
                secretKeyRef:
                  name: calendar-mail-secret
                  key: smtp-pass

            - name: MAIL_FROM
              valueFrom:
                secretKeyRef:
                  name: calendar-mail-secret
                  key: mail-from
          readinessProbe:
            httpGet:
              path: /stats
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /stats
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20