apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS users (
        id SERIAL PRIMARY KEY,
        name VARCHAR(100) NOT NULL,
        email VARCHAR(100) UNIQUE NOT NULL,
        password_hash TEXT NOT NULL,
        global_role VARCHAR(20) NOT NULL DEFAULT 'member',
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS calendars (
        id SERIAL PRIMARY KEY,
        user_id INT REFERENCES users(id) ON DELETE CASCADE,
        name VARCHAR(100) NOT NULL,
        description TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS events (
        id SERIAL PRIMARY KEY,
        calendar_id INT REFERENCES calendars(id) ON DELETE CASCADE,
        title VARCHAR(255) NOT NULL,
        description TEXT,
        start_time TIMESTAMP NOT NULL,
        end_time TIMESTAMP NOT NULL,
        location VARCHAR(255),
        status VARCHAR(20) DEFAULT 'scheduled',
        CHECK (status IN ('scheduled', 'cancelled', 'completed')),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS calendar_shares (
        id SERIAL PRIMARY KEY,
        calendar_id INT REFERENCES calendars(id) ON DELETE CASCADE,
        user_id INT REFERENCES users(id) ON DELETE CASCADE,
        permission VARCHAR(50) NOT NULL CHECK (permission IN ('viewer', 'editor')),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        UNIQUE (calendar_id, user_id)
    );
    
    
    CREATE TABLE IF NOT EXISTS event_participants (
        id SERIAL PRIMARY KEY,
        event_id INTEGER REFERENCES events(id) ON DELETE CASCADE,
        user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
        role VARCHAR(20) DEFAULT 'attendee',
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        UNIQUE (event_id, user_id)
    );

    INSERT INTO users (name, email, password_hash, global_role)
    VALUES (
        'John Doe',
        'john@example.com',
        '$2b$10$replace_with_real_bcrypt_hash',
        'member'
    )
    ON CONFLICT (email) DO NOTHING;

    INSERT INTO calendars (user_id, name)
    VALUES (1, 'Work')
    ON CONFLICT DO NOTHING;

    INSERT INTO events (calendar_id, title, start_time, end_time)
    VALUES (1, 'Initial Event', '2026-03-01 10:00:00', '2026-03-01 12:00:00');